INSERT INTO public.recipes ("name","type",slot,tags,cookidooid,menu_id) VALUES
                                                                             ('Alubias con gambas','legumbres','any','','r65016',1),
                                                                             ('Berenjenas rellenas con alubias y tomate','legumbres','any','','r696375',1),
                                                                             ('Callos veganos (setas con garbanzos)','legumbres','any','','r322159',1),
                                                                             ('Curry de champiñones y garbanzos con espinacas','legumbres','any','','r595986',1),
                                                                             ('Ensalada de garbanzos con cebolla caramelizada','legumbres','any','','r596650',1),
                                                                             ('Espinacas con garbanzos a la sevillana','legumbres','any','','r47649',1),
                                                                             ('Garbanzos con rape y crujiente de cecina','legumbres','any','','r78292',1),
                                                                             ('Garbanzos con tomate, piquillos y atún','legumbres','any','','r563027',1),
                                                                             ('Guisado de lentejas etíope (Misir wat)','legumbres','any','','r723858',1),
                                                                             ('Guiso de coliflor y garbanzos','legumbres','any','','r939255',1);
INSERT INTO public.recipes ("name","type",slot,tags,cookidooid,menu_id) VALUES
                                                                             ('Guiso de garbanzos con sepia y langostinos','legumbres','any','','r489830',1),
                                                                             ('Guiso de garbanzos con verduras y chorizo','legumbres','any','','r55732',1),
                                                                             ('Guiso de lentejas y alubias con verduras','legumbres','any','','r49882',1),
                                                                             ('Guiso de lentejas y champiñones','legumbres','any','','r793681',1),
                                                                             ('Lentejas guisadas','legumbres','any','','r49017',1),
                                                                             ('Potaje de garbanzos con kale y gambones','legumbres','any','','r424595',1),
                                                                             ('Potaje de verduras, pasta y alubias rojas','legumbres','any','','r148971',1),
                                                                             ('Ensalada con queso de cabra y aderezo de nuez de la india','verduras','any','','r720505',1),
                                                                             ('Ensalada de brócoli, pimiento y manzana','verduras','any','','r722099',1),
                                                                             ('Ensalada de espárragos y fresas','verduras','any','','r320149',1);
INSERT INTO public.recipes ("name","type",slot,tags,cookidooid,menu_id) VALUES
                                                                             ('Ensalada de quinoa y judías negras','verduras','any','','r920493',1),
                                                                             ('Ensalada de tomate con ventresca','verduras','any','','r900311',1),
                                                                             ('Ensalada fresca de quinoa','verduras','any','','r149583',1),
                                                                             ('Ensalada verde con aderezo de jamaica','verduras','any','','r140714',1),
                                                                             ('Pollo balsámico con salteado verduras','verduras','any','','r511969',1),
                                                                             ('Quinoa con verduras salteadas','verduras','any','','r21607',1),
                                                                             ('Salteado de verduras al curry','verduras','any','','r700048',1),
                                                                             ('Salteado de verduras con salsa de cacahuetes','verduras','any','','r751924',1),
                                                                             ('Salteado de verduras mixtas','verduras','any','','r507711',1),
                                                                             ('Tinga de pollo y ensalada de calabacitas','verduras','any','','r921894',1);
INSERT INTO public.recipes ("name","type",slot,tags,cookidooid,menu_id) VALUES
                                                                             ('Wraps con verduras salteadas y crema de hierbas','verduras','any','','r799684',1),
                                                                             ('Arroz cremoso de gambones, salmón y verduras','pescado','any','','r450038',1),
                                                                             ('Filetes rusos de salmón rellenos de gruyère al horno con ensalada','pescado','any','','r129296',1),
                                                                             ('Fingers de merluza con salsa de tomate','pescado','any','','r103983',1),
                                                                             ('Hamburguesa de merluza y gambón','pescado','any','','r69648',1),
                                                                             ('Merluza a la gallega','pescado','any','','r16605',1),
                                                                             ('Merluza con espinacas, gambas y salsa de piquillos','pescado','any','','r430766',1),
                                                                             ('Merluza con gambas en salsa de puerros','pescado','any','','r512337',1),
                                                                             ('Merluza en salsa verde con gambas y chirlas','pescado','any','','r48926',1),
                                                                             ('Merluza rellena con ajada de gambas','pescado','any','','r42280',1);
INSERT INTO public.recipes ("name","type",slot,tags,cookidooid,menu_id) VALUES
                                                                             ('Puré de calabaza, patata y puerro con merluza','pescado','any','','r122343',1),
                                                                             ('Salmón a la naranja con cuscús de brócoli','pescado','any','','r129295',1),
                                                                             ('Salmón al vapor con glaseado de soya y jengibre','pescado','any','','r753773',1),
                                                                             ('Salmón al vapor y arroz basmati con salsa crema de eneldo','pescado','any','','r129298',1),
                                                                             ('Salmón con costra de almendras y pappardelle con espárragos','pescado','any','','r129293',1),
                                                                             ('Salmón con salsa de balsámico y zoodles de calabacín','pescado','any','','r129294',1),
                                                                             ('Salmon en croûte con risotto de limón','pescado','any','','r129300',1),
                                                                             ('San jacobo de merluza al vino blanco con berberechos para dos','pescado','any','','r147137',1),
                                                                             ('Espagueti a la boloñesa','pasta','any','','r146353',1),
                                                                             ('Espagueti carbonara','pasta','any','','r374300',1);
INSERT INTO public.recipes ("name","type",slot,tags,cookidooid,menu_id) VALUES
                                                                             ('Espagueti con aceite de oliva, ajo y perejil','pasta','any','','r146354',1),
                                                                             ('Espagueti con champiñones y tocino','pasta','any','','r66035',1),
                                                                             ('Espagueti con salsa de tomate y atún','pasta','any','','r132711',1),
                                                                             ('Espaguetis a la amatriciana','pasta','any','','r108862',1),
                                                                             ('Espaguetis a las hierbas aromáticas con queso crema','pasta','any','','r595345',1),
                                                                             ('Espaguetis con albóndigas (La dama y el vagabundo)','pasta','any','','r577935',1),
                                                                             ('Espaguetis con pimientos','pasta','any','','r108873',1),
                                                                             ('Espaguetis con salchichas frescas y pimiento rojo','pasta','any','','r631292',1),
                                                                             ('Espaguetis con salsa de queso y espinacas','pasta','any','','r773079',1),
                                                                             ('Pasta "alla Norma"','pasta','any','','r113149',1);
INSERT INTO public.recipes ("name","type",slot,tags,cookidooid,menu_id) VALUES
                                                                             ('Pasta al pomodoro, prosciutto e salame piccante','pasta','any','','r214946',1),
                                                                             ('Pasta e piselli','pasta','any','','r208757',1),
                                                                             ('Pasta mista napoletana con sugo di fagioli','pasta','any','','r66562',1),
                                                                             ('Tomato Basil Pasta','pasta','any','','r161846',1),
                                                                             ('Cazuela de patatas con pollo','carne','any','','r37812',1),
                                                                             ('Entrecot de ternera con ensalada campera','carne','any','','r726017',1),
                                                                             ('Estofado de ternera con cerveza','carne','any','','r936740',1),
                                                                             ('Involtini di pancetta, pollo e scamorza','carne','any','','r116125',1),
                                                                             ('Palomitas de pollo','carne','any','','r254050',1),
                                                                             ('Pollo a la tapenade con puré de papa y cebolla caramelizada','carne','any','','r130577',1);
INSERT INTO public.recipes ("name","type",slot,tags,cookidooid,menu_id) VALUES
                                                                             ('Pollo al estilo marroquí con cuscús (Melilla)','carne','any','','r55904',1),
                                                                             ('Pollo asado con verduras en salsa de sidra','carne','any','','r909521',1),
                                                                             ('Pollo frito al estilo Kentucky','carne','any','','r52926',1),
                                                                             ('Pollo in umido ai funghi','carne','any','','r85446',1),
                                                                             ('Rollitos de ternera rellenos de jamón y pepinillos con lombarda','carne','any','','r616087',1),
                                                                             ('Solomillo de ternera con salsa de cerezas al Oporto','carne','any','','r827265',1),
                                                                             ('Solomillo de ternera en papillote con salsa de vermut','carne','any','','r43835',1),
                                                                             ('Tayín de ternera con arroz especiado y mini pasteles de pistacho','carne','any','','r822962',1),
                                                                             ('Ternera asada especiada con puré de patata, tomates secos y salsa de vino tinto (MEATER)','carne','any','','r481540',1),
                                                                             ('Ternera con salsa de atún (Vitello tonnato) para dos','carne','any','','r129632',1);
INSERT INTO public.recipes ("name","type",slot,tags,cookidooid,menu_id) VALUES
                                                                             ('Arroz caldoso con especias','arroz','any','','r17477',1),
                                                                             ('Arroz con atún','arroz','any','','r37784',1),
                                                                             ('Arroz negro cremoso con calamares','arroz','any','','r21719',1),
                                                                             ('Arroz tres delicias','arroz','any','','r18428',1),
                                                                             ('Paella de marisco','arroz','any','','r697376',1),
                                                                             ('Paella de verduras','arroz','any','','r121101',1),
                                                                             ('Paella valenciana','arroz','any','','r307322',1),
                                                                             ('Sepia en salsa de verduras con guarnición de arroz','arroz','any','','r36901',1),
                                                                             ('Sopa de pescado y arroz','arroz','any','','r40272',1),
                                                                             ('Tacos de lechuga con arroz y camarón','arroz','any','','r78632',1);
INSERT INTO public.recipes ("name","type",slot,tags,cookidooid,menu_id) VALUES
                                                                             ('Cacerola de pollo','cena','any','','r462480',1),
                                                                             ('Coca de chipirones y boletus al ajillo','cena','any','','r148310',1),
                                                                             ('Guisantes con jamón','cena','any','','r40265',1),
                                                                             ('Judías verdes al vapor con pollo en salsa y cacahuetes','cena','any','','r123150',1),
                                                                             ('Pasta con camarones y chorizo','cena','any','','r462477',1),
                                                                             ('Poke bowl de atún spicy','cena','any','','r459341',1),
                                                                             ('Pollo teriyaki','cena','any','','r462483',1),
                                                                             ('Salmón con salsa de frambuesa y espárragos','cena','any','','r462475',1),
                                                                             ('Sopa de tortilla','cena','any','','r236246',1),
                                                                             ('Tortilla','cena','any','','r154276',1);
